# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: 'S:\Shotgun\0000_sg_development'
Darwin: '/Volumes/Cache/Shotgun/0000_sg_development'
Linux: '/Volumes/Cache/Shotgun/0000_sg_development'

# End of file.
